# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_recode.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Recoding(object):
    def setupUi(self, Recoding):
        Recoding.setObjectName("Recoding")
        Recoding.resize(233, 195)
        self.layoutWidget = QtWidgets.QWidget(Recoding)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 171, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.state_label = QtWidgets.QLabel(self.layoutWidget)
        self.state_label.setObjectName("state_label")
        self.gridLayout.addWidget(self.state_label, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.endKey = QtWidgets.QLabel(self.layoutWidget)
        self.endKey.setObjectName("endKey")
        self.gridLayout.addWidget(self.endKey, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.startKey = QtWidgets.QLabel(self.layoutWidget)
        self.startKey.setObjectName("startKey")
        self.gridLayout.addWidget(self.startKey, 1, 1, 1, 1)

        self.retranslateUi(Recoding)
        QtCore.QMetaObject.connectSlotsByName(Recoding)

    def retranslateUi(self, Recoding):
        _translate = QtCore.QCoreApplication.translate
        Recoding.setWindowTitle(_translate("Recoding", "录制"))
        self.state_label.setText(_translate("Recoding", "未运行"))
        self.label_5.setText(_translate("Recoding", "结束热键："))
        self.endKey.setText(_translate("Recoding", "F10"))
        self.label_4.setText(_translate("Recoding", "启动热键："))
        self.label.setText(_translate("Recoding", "当前状态:"))
        self.startKey.setText(_translate("Recoding", "F9"))
