# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EventMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_EventMenu(object):
    def setupUi(self, Ui_EventMenu):
        Ui_EventMenu.setObjectName("Ui_EventMenu")
        Ui_EventMenu.resize(235, 191)
        self.formLayoutWidget = QtWidgets.QWidget(Ui_EventMenu)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 188, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.layoutWidget = QtWidgets.QWidget(Ui_EventMenu)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 150, 194, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_acept = QtWidgets.QPushButton(self.layoutWidget)
        self.Button_acept.setObjectName("Button_acept")
        self.horizontalLayout.addWidget(self.Button_acept)
        self.Button_refuse = QtWidgets.QPushButton(self.layoutWidget)
        self.Button_refuse.setObjectName("Button_refuse")
        self.horizontalLayout.addWidget(self.Button_refuse)
        self.toolButton = QtWidgets.QToolButton(Ui_EventMenu)
        self.toolButton.setGeometry(QtCore.QRect(210, 10, 23, 22))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../picture/help.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(16, 16))
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Ui_EventMenu)
        self.Button_refuse.clicked.connect(Ui_EventMenu.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Ui_EventMenu)

    def retranslateUi(self, Ui_EventMenu):
        _translate = QtCore.QCoreApplication.translate
        Ui_EventMenu.setWindowTitle(_translate("Ui_EventMenu", "新建事件"))
        self.label.setText(_translate("Ui_EventMenu", "序号"))
        self.label_2.setText(_translate("Ui_EventMenu", "事件类型"))
        self.comboBox.setItemText(0, _translate("Ui_EventMenu", "按键"))
        self.comboBox.setItemText(1, _translate("Ui_EventMenu", "鼠标移动"))
        self.comboBox.setItemText(2, _translate("Ui_EventMenu", "延时"))
        self.comboBox.setItemText(3, _translate("Ui_EventMenu", "运行指定脚本"))
        self.label_3.setText(_translate("Ui_EventMenu", "按键"))
        self.lineEdit.setToolTip(_translate("Ui_EventMenu", "<html><head/><body><p><br/></p></body></html>"))
        self.label_4.setText(_translate("Ui_EventMenu", "状态"))
        self.Button_acept.setText(_translate("Ui_EventMenu", "保存"))
        self.Button_refuse.setText(_translate("Ui_EventMenu", "取消"))
        self.toolButton.setToolTip(_translate("Ui_EventMenu", "<html><head/><body><p>文件路径提示：当前文件路径直接使用文件名称</p><p>当前目录文件路径使用 ./ 代替前置目录</p><p>绝对路径使用 C:\\PycharmProjects\\脚本\\测试1</p></body></html>"))
        self.toolButton.setText(_translate("Ui_EventMenu", "?"))
